### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by osivinyuk** [Lunars/tesla#20]
Could you give an instruction how to put crontab with scripts to mcu tegra

**Comment by Geczy** [comment]
Readme has been updated to add instructions :) 

https://github.com/Lunars/tesla/blob/master/README.md

**Comment by osivinyuk** [comment]
I understand it, but how you get root access to tesla@cid?

**Comment by Geczy** [comment]
https://github.com/jnuyens/freedomev/blob/master/README.md

Check the faq at the bottom

**Comment by osivinyuk** [comment]
thank you so much
