### ISSUE TITLE
how to write message into IC

### ISSUE THREAD

**Issue by Baha2Odeh** [Lunars/tesla#26]
Hi
I have root access to my car
I want to write a message or display custom image ON IC

**Comment by Geczy** [comment]
I don't know what this means, you'll have to be more descriptive

**Comment by Baha2Odeh** [comment]
> I don't know what this means, you'll have to be more descriptive
Hi
I have root access to my car
I want to write a message or display custom image ON IC

**Comment by Geczy** [comment]
https://github.com/Lunars/tesla/blob/master/src/scripts/forever/listen-for-code.sh#L49

This is example for CID, I don't know how to do IC

**Comment by Baha2Odeh** [comment]
> https://github.com/Lunars/tesla/blob/master/src/scripts/forever/listen-for-code.sh#L49
> 
> This is example for CID, I don't know how to do IC

I tried it it is working on CID waiting for any one to help how to write something on IC

**Comment by Geczy** [comment]
Like an alert message on IC?

**Comment by Baha2Odeh** [comment]
> Like an alert message on IC?

Yes

**Comment by Geczy** [comment]
You can only do it through CAN, not possible from ssh
