### ISSUE TITLE
Does the car software autodetect the heated wheel?

### ISSUE THREAD

**Issue by glynhudson** [Lunars/tesla#35]
Once fitted does the car software automatically detect the heated wheel? I.e does the heated wheel control icon appear on the touchscreen app?

I'm considering fitting a heated wheel to my MS60 which was made in December 2016, am I correct in thinking that the wiring harness for the heated connection will already in place?

**Comment by Geczy** [comment]
No, you have to enable the icon yourself

Yes, your car will have the wiring harness already. But probably not the SCCM pinout

The command to run is inside the file under Config https://github.com/Lunars/tesla/blob/master/retrofit/subzero/heated-wheel.md

**Comment by glynhudson** [comment]
Got it. I'm assuming enabling the icon functionality will require root? 

I wonder if Tesla would be enable the functionality on a non rooted car? 

Do you have any info on what scripts would be needed to enable the icon functionality if root was available? 

Thanks

**Comment by Geczy** [comment]
The link I gave gives the command to enable it. No, Tesla won't. Yes, requires root.
