### ISSUE TITLE
emit-reboot-cid boot hangs

### ISSUE THREAD

**Issue by F-John** [Lunars/tesla#46]
I'm having an issue when I emit a reboort for the CID where the car doesn't turn on after 5, 10, or even 30 minutes.
In order to get the car started I need to do a double scroll wheel reset to have any of the screens come up.

**Comment by jeankalud** [comment]
Try the “reboot” command instead and if same result you should think about having your eMMC replaced. Weird boot behaviour are almost eMMC related, corruption, etc. It probably do fsck during boot to check files and maybe even just hang

**Comment by F-John** [comment]
Emmc has already been replaced.

**Comment by jeankalud** [comment]
Ok well... use reboot instead

**Comment by F-John** [comment]
Reboot works, but I know it’s not as graceful as emit-reboot. I’d like to troubleshoot that issue if someone could help me with that troubleshooting I think it will help others who may get this issue.

**Comment by rafcabezas** [comment]
@F-John what's happening to you is that you probably have softpanda and you're not removing the lock before rebooting.

**Comment by F-John** [comment]
@rafcabezas I'll look into that. See if that fixes it.... but before Lunars, I never had such an issue.

**Comment by rafcabezas** [comment]
There's a safety measure in softpanda. From the docs: "The softPanda startup script creates a lock file and prevents two restarts in less than 10 minutes to allow you to still access your car computers in the event of a mistake. To manually restart the process you have to delete the lock file and then kill the softPanda process." I'm thinking you probably hit this scenario.

**Comment by F-John** [comment]
@rafcabezas for the first restart in three days, it shouldn't cause any issues.

**Comment by rafcabezas** [comment]
shouldn't, no.

**Comment by F-John** [comment]
I have to try another ```emit-reboot-cid``` at some point, but I think this may have just been a poorly optimized crontab.

**Comment by F-John** [comment]
Nope. I was wrong. First restart in a few days but still hanging.

**Comment by Geczy** [comment]
This isn't Lunars related
