### ISSUE TITLE
Does this install work on 8.1 without issues? 

### ISSUE THREAD

**Issue by bigggibb** [Lunars/tesla#48]
Anyone else have problems  using the scripts with older versions on Model S.  I'm still on 8.1. Seems like the cron is not running the on-reboot.sh during reboot.  If I run the scripts individually some will run. Thanks

**Comment by F-John** [comment]
@bigggibb can you copy your crontab here?
Let’s take a look.

**Comment by bigggibb** [comment]
I will post tomorrow.

**Comment by bigggibb** [comment]
> @bigggibb can you copy your crontab here?
> Let’s take a look.

I think I'm good now. I didn't realize I had to edit the on-reboot.sh "mydir=/path" . Once I did that all the other scripts were able to pull in the information I put on the config.sh. I dont know if that's normal or not. I thought the install would link everything.  I'm learning so don't beat me up. ;-)

By the way I wasn't able to just install it using the link in the readme.  I kept getting the error when it was at the download. I guess the setting on github didn't agree with the cars curl settings.  I just hosted the files on my home website and then was able to install. 

Thanks for the willingness to help!

**Comment by F-John** [comment]
@bigggibb older firmwares don’t support curl, so you did exactly what would have been recommended. 

Readme.md needs an update to include that workaround.

**Comment by bigggibb** [comment]
> @bigggibb older firmwares don’t support curl, so you did exactly what would have been recommended.
> 
> Readme.md needs an update to include that workaround.

I agree! It took me a long time to figure that one out! I guess I can close this issue out now?

**Comment by bigggibb** [comment]
> @bigggibb can you copy your crontab here?
> Let’s take a look.

@F-John  would you have a way I can contact you. I'm have the issue again with the export information on the config.sh file is not getting pulled in to the other scripts. Particularly the save-token by  ssh one.i got it to work once. But after the reboot it stopped.

**Comment by Geczy** [comment]
Run `source config.sh` before running any Lunars scripts manually
