### ISSUE TITLE
Lunars tmpfs should be wiped every hour

### ISSUE THREAD

**Issue by F-John** [Lunars/tesla#49]
tmpfs wiping every hour: https://tinkla.us/index.php/Root:Move_logs_to_tmpfs
The script page on tinkla recommends a crontab change ```11 * * * * cat /dev/null > /var/log/syslog ; cat /dev/null > /var/log/openvpn.log```
But I don't see that as one of the lines in the Lunars crontab. Maybe Lunars isn't wiping the ram and just letting it fill?

This can cause issues, especially for the listen-for-code.sh

**Comment by Geczy** [comment]
Doesn't logrotate take care of any issues there for us? 

```bash
root@cid# cat /etc/logrotate.d/rsyslog
/var/log/syslog
```
