### ISSUE TITLE
Offline/Online

### ISSUE THREAD

**Issue by F-John** [Lunars/tesla#50]
Big issue with the listen-for-code.sh “offline” and “online” passwords:
On-reboot.sh won’t start Lunars until it can check for an update, and since both of those T-Passwords reboot the CID, once the car goes offline then there is no way to run the online password without a connection. 

Can a change be made to the On-reboot.sh to start listen-for-code.sh no matter what? Or just check if Offline is activated and start listen-for-code.sh before internet connection in those cases?

**Comment by F-John** [comment]
Current workaround in cron:
`@reboot /bin/bash [lunars-dir]/scripts/everyBoot/listen-for-code.sh`

When the car boots next, that will also start the listen for code script, so even if you don’t have internet you can still run codes.

**Comment by LukeNL** [comment]
It does start the scripts, but only after 5 tries (+ 1 minute sleep delay) to check internet connectivity. In offline situation it will take a total of about 10 minutes after reboot to start all the scripts.

**Comment by Geczy** [comment]
As @LukeNL said, Lunars checks for internet for 5 minutes then continues if none is found. https://github.com/Lunars/tesla/blob/master/src/scripts/on-reboot.sh#L40
