### ISSUE TITLE
2019.16.3.2 crontab problem

### ISSUE THREAD

**Issue by GENOV7** [Lunars/tesla#52]
Does anybody have problem with crontab , here i can install all and all work corect till one reboot of CID after reboot i must install all again or run manually on-reboot script maybe someone can help me with this .

**Comment by Baha2Odeh** [comment]
Tesla mounted cron on swap after 2019.16 so everything is lost after reboot

**Comment by GENOV7** [comment]
Do you know how to downgrade it to 2018.42 for example , i install it on updater but everytime have error when i try factory-redeploy

**Comment by LukeNL** [comment]
You can't downgrade to a lower security version (check file in /deploy/security-version) using cid installer. You can however downgrade to 2018.50.6 if you dd the lower firmware to the offline bank, flashcp the correct kernel to the offline nor bank (mtd9/10), and modify the mtd7 (env) to boot from the offline bank (or use cid installer setenv) . After reboot do a service-redeploy and the car will be on the lower firmware.
However you can't go much further back then 2018.50.6, I have recently tried to downgrade to 2018.34 on a car and it failed when trying to redeploy.
Good luck.

**Comment by jnuyens** [comment]
> You can't downgrade to a lower security version (check file in /deploy/security-version) using cid installer. 

Is it possible to first bind mount a lower security version, and then downgrade? For example:
echo 1 > /var/security-version
mount --bind /var/security-version /usr/deploy/security-version

Didn't try it yet ;)

**Comment by GENOV7** [comment]
What is the best to run after reboot to start lunars again , bash on-reboot.sh not work correct for me - i see that script start on console but dont actually run all the scripts from config.sh .
This is was actually happen :
Welcome to Ubuntu!
 * Documentation:  https://help.ubuntu.com/
Last login: Sat Feb  1 08:42:57 2020 from ic
tesla1@cid-XXXXXXXXXXXXXXX$ sudo su
root@cid-XXXXXXXXXXXXXXX# cd /var/lunars/scripts
root@cid-XXXXXXXXXXXXXX# bash on-reboot.sh
on-reboot.sh: line 5: on-reboot.sh/../config.sh: Not a directory
Starting Lunars
Waiting for internet before continuing...
Found internet
Continuing with Lunars startup
Waiting 5 minutes...

**Comment by GENOV7** [comment]
When i "curl" repo again to install it then all work just fine but i don't think that this is the right way .

**Comment by GENOV7** [comment]
Can someone share 2018.50 - I don't have it

**Comment by Geczy** [comment]
If you need 2018.50.6 send me a message

```bash
homeOfLunars="/var/lunars"
onRebootFile="$homeOfLunars/scripts/$rebootScript"
startScript="/sbin/start-stop-daemon --start --quiet --make-pidfile --oknodo --background --pidfile /var/run/lunars-main.pid --exec /bin/bash $onRebootFile"
```

This is how you start the script

**Comment by The-Synthax** [comment]
> > You can't downgrade to a lower security version (check file in /deploy/security-version) using cid installer.
> 
> Is it possible to first bind mount a lower security version, and then downgrade? For example: echo 1 > /var/security-version mount --bind /var/security-version /usr/deploy/security-version
> 
> Didn't try it yet ;)

Since no one replied to this, yes, it works perfectly!
