### ISSUE TITLE
FactoryMode

### ISSUE THREAD

**Issue by maslakandrey** [Lunars/tesla#53]
Is it possible to turn on the factory mode without root access?

**Comment by GENOV7** [comment]
Not possible without root , maybe possible to be activated with Toolbox .

**Comment by maslakandrey** [comment]
No, I know that it is possible to start the factory mode without root, but how ...

**Comment by TSorokivskyi** [comment]
Yes it possible, without root.

**Comment by maslakandrey** [comment]
> Yes it possible, without root.

and how to find out for a fee?
