### ISSUE TITLE
vpn-over-cell

### ISSUE THREAD

**Issue by bigggibb** [Lunars/tesla#54]
Is the ssh port "22" for VPN over cell? I keep getting connection refused when trying to ssh to the car from my computer. I'm using the ip my VPN server assigned the car once its connected  to the VPN server (10.8.0.10) I'm able to ping the car using the IP but still unable to connect via ssh. To make sure it wasn't just the server,  I tested the ssh on a older Mac laptop to see if I could ssh into it using the assigned ip from the vpn tunnel. It worked fine.

**Comment by Baha2Odeh** [comment]
You need to allow connection to port 22 over this connection using iptable 
Check ifconfig to get your tun name let us assume it tun2 


/sbin/iptables -D INPUT -i tun2 -p tcp --dport 22 -j ACCEPT 

/sbin/iptables -I INPUT -i tun2 -p tcp --dport 22 -j ACCEPT

**Comment by bigggibb** [comment]
> You need to allow connection to port 22 over this connection using iptable
> Check ifconfig to get your tun name let us assume it tun2
> 
> /sbin/iptables -D INPUT -i tun2 -p tcp --dport 22 -j ACCEPT
> 
> /sbin/iptables -I INPUT -i tun2 -p tcp --dport 22 -j ACCEPT

@Baha2Odeh thanks Do I make these changes on my server in or the car end?

**Comment by Baha2Odeh** [comment]
> > You need to allow connection to port 22 over this connection using iptable
> > Check ifconfig to get your tun name let us assume it tun2
> > /sbin/iptables -D INPUT -i tun2 -p tcp --dport 22 -j ACCEPT
> > /sbin/iptables -I INPUT -i tun2 -p tcp --dport 22 -j ACCEPT
> 
> @Baha2Odeh thanks Do I make these changes on my server in or the car end?

On your car

**Comment by bigggibb** [comment]
@Baha2Odeh I edited the tesla.opvn file with the correct tun# and it worked . Thanks for the help!

**Comment by bigggibb** [comment]
Non-issue user error!
