### ISSUE TITLE
php not working 

### ISSUE THREAD

**Issue by bigggibb** [Lunars/tesla#55]
I'm having trouble with the php files I uploaded to my server. I'm trying to get the save-token and save-vitals scripts to work. When I open the save-vitals.php in the browser it displays a blank white screen . When I open the  save-token.php page it displays a message fopen (.tesla_tokens.json): failed to open stream: permissions denied can't create file. Am I doing something wrong or missing some software?  Do I need a database like Mysql to make this work? I'm pretty new to php. Thanks

**Comment by Geczy** [comment]
Don't open them in your browser, your car will use them to save files

**Comment by bigggibb** [comment]
Where is the file saved at? On the server or car?

**Comment by Geczy** [comment]
Server

**Comment by bigggibb** [comment]
Okay,  it saves the file it as the "file name" input on the config.sh correct?

**Comment by bigggibb** [comment]
Still haven't figured this out. Do I have to modified the save-vitals.php file to work on my server or should it work as is? Seems like I'm missing a step. Car makes connection with url link  from config.sh. I just don't know where the file it generates is supposed to be saved at on the server.
