### ISSUE TITLE
Lock / Unlock the car

### ISSUE THREAD

**Issue by mgoeller** [Lunars/tesla#56]
I would like to get rid of my key for my Model X and be able to reliable unlock the car with just my phone. How can I trigger the unlock signal for my car? The wiki states about unlocking/locking under the canbus section. So I don't even need root access and can just send a telegram on the CAN bus?

**Comment by Geczy** [comment]
```curl -H "X-SSL-Client-S-CN:$(cat /var/etc/vin)" http://cid:7654/door_unlock```

**Comment by mgoeller** [comment]
Thank you very much Geczy! I guess the access to the car is only possible if the fakra ethernet port is activated, right? As far as I understood one of the scripts from lunars opens this ethernet port every time the CID boots up. And those scripts can only be put on the filesystem if I have root access, correct?

Is it also possible to open the doors over the CAN2 bus? According to this [link](https://teslatap.com/undocumented/) there is a "CAN2 – Body, 125 kbps" bus, that is amongst other things responsible for the "Door controllers". Can I just record and replay the signal on that bus? I guess the curl command that I send to the CID is in the end also just sending the door opener signal on the CAN2 bus via the gateway if I understood correctly?

And what about this information from the wiki? Are these commands sent from the MCU to the Gateway?

> lock/unlock car:
> lock: sdv GUI_lockRequest lock
> unlock: sdv GUI_lockRequest unlock
> The rest below only works when you're sitting in the driver's seat, AFAIK

Thank you for you help and info!
