### ISSUE TITLE
service-redeploy after CID replacement

### ISSUE THREAD

**Issue by MaxxxU** [Lunars/tesla#59]
I have model X 2016 AP1. My tegra and EMMC completely dead and I replaced it to CID from another MX.
In my car the firmware version was 2018.50.6 and in replaced CID version of firmware is 2018.34.1
I put a new CID to my MCU and tried to do service-redeploy.
But the service-redeploy failed. 

[Error](http://79.143.47.26/error.png)

What I am doing wrong?

**Comment by Baha2Odeh** [comment]
so you completely replaced the CID? I think you should update the gateway config from the old CID, copy the VIN and other car configuration

**Comment by MaxxxU** [comment]
I have no old configs from CID because EMMC is [dead](http://79.143.47.26/dead.jpg). I am copied a gw config /var/etc/gateway.cfg and modify /var/etc/vin but service-redeploy failed

**Comment by MaxxxU** [comment]
I  need 2018.50.6   Can someone share it for me?

**Comment by Baha2Odeh** [comment]
> I need 2018.50.6 Can someone share it for me?

Discord : bahaaodeh

**Comment by MaxxxU** [comment]
> > I need 2018.50.6 Can someone share it for me?
> 
> Discord : bahaaodeh

Hi, Baha2Odeh
I mailed you about firmware, did you see my message?

**Comment by Geczy** [comment]
you're gonna have to copy the gateway config and carkeys over, or at least match the gateway config as closely as possible before the redeploy will work
