### ISSUE TITLE
Upgrade to latest version. Challenges ahead?  

### ISSUE THREAD

**Issue by lau85** [Lunars/tesla#60]
I have early 2013 model S without AP. Version 8 with root access, but planning to upgrade firmware to some later version. Main reason - VPN should stop working soon with my current version soon.
What version is the best at this time the most easy to work with? I know that with latest versions tesla can disable fast charge (chademo) and it will not be that easy to re-enable it again.
Just looking for recommendations as this must be important question at this time.

**Comment by TSorokivskyi** [comment]
You need to have install at least 2019.40. I don't know if it is possible run crontab on this version.

**Comment by lau85** [comment]
It should not be possible to run cron, but there are other ways to keep root. Haven't tested it yet, but planning to do it on weekend. Still waiting for some tips.

**Comment by Baha2Odeh** [comment]
> It should not be possible to run cron, but there are other ways to keep root. Haven't tested it yet, but planning to do it on weekend. Still waiting for some tips.

You are right its not possible to keep root, but there is some way which i don't know unfortunately
