### ISSUE TITLE
looking for MCU1 firmware

### ISSUE THREAD

**Issue by The-Synthax** [Lunars/tesla#76]
Hello, I'm in need of 2020.36 or older to downgrade to.

**Comment by martiinezz** [comment]
2020.36.16 ??

**Comment by The-Synthax** [comment]
> 2020.36.16 ??

That's the one!

**Comment by The-Synthax** [comment]
Looking for 2019.12 or 2019.15

**Comment by The-Synthax** [comment]
My Discord is Synthax#0001
