### ISSUE TITLE
Signature Issue When Manually Updating the Software

### ISSUE THREAD

**Issue by strmotors** [Lunars/tesla#81]
Hello everyone, I am trying to update my Tesla Model S with Tegra MCU2, rooted (2020.36.11). I have a software image (2022.10.11) which is claimed by installing to another Tesla using cid-updater. When I try to locally serve the image and install using cid-updater, it says signatures are invalid. How can I overcome this issue? What solution method should I concentrate:

- Patching the cid-updater binary in order to skip the 'verifysig' event
- Editing the software image to change its base64 signature
- Downgrading to an older version with a vulnerable cid-updater and make the signatures pass
- Any other thing you would offer

Alternatively, I could manually write the software image to the EMMC. But how can I deploy the software to other ECUs without the signature check? After all, the software should be staged.

**Comment by stiffler-m** [comment]
hi. you need to install intermediate firmware first. for example, first 2020.48.37.8, then 2021.24.28, and I recommend stopping at 2022.8.10.5 (factory mode is disabled in the following firmware)

**Comment by strmotors** [comment]
Thank you very much for your response. I will try to install the medium software first.

Peace.
